### PR TITLE
Support aXe-core 3.0 Shadow DOM selectors

### PR DESCRIPTION
**Pull request by WilcoFiers**

### CODE REVIEW

**Comment by marcysutton** [comment]
I really wish we had more tests for this project! Any way we can add them with this change to make sure it works?

**Comment by WilcoFiers** [comment]
@marcysutton You're quite right. I've added an integration test showing it picks up shadow DOM elements.

**Comment by marcysutton** [comment]
@WilcoFiers I think you need to upgrade the Node version on Circle, transpile with Babel, or use more stable JS APIs.

**Comment by WilcoFiers** [comment]
Sorted. Sorry Marcy, bit of an oversight on my part.

**Pull request merged**
