### PR TITLE
ci: auto-release `master` commits

### PR DESCRIPTION
**Pull request by stephenmathieson**
This patch configures CircleCI to automatically release all commits to the `master` branch to npm.

It is expected that commits landing in `master` have already updated `package.json#version` and made the necessary changes to `CHANGELOG.md`.

### CODE REVIEW

**Comment by stephenmathieson** [comment]
> also this project has no .github templates?

You never merged https://github.com/dequelabs/axe-cli/pull/69 😺

**Comment by jkodu** [comment]
@stephenmathieson - yeah build kept kicking the bucket.... Meh!

**Comment by stephenmathieson** [comment]
@WilcoFiers @dylanb can either of you update the CircleCI settings for this repo? New jobs have been created which broke the existing settings.

**Comment by WilcoFiers** [comment]
Reviewed for security by @wilcofiers

**Pull request merged**
