### PR TITLE
Fix axe-source option

### PR DESCRIPTION
**Pull request by WilcoFiers**
This fixes a couple of problems:

- axe-source didn't work (it was never supposed to, I forgot to comment it out, but it's easy enough to solve, so I've added it).
- add unit tests
- add a circle file
- fix spacing/tab inconsistency
- bump to 1.1.0

### CODE REVIEW

**Comment by dylanb** [comment]
Any way we can get circle CI builds to run our tests?

**Comment by dylanb** [comment]
Ah, Circle is running the tests and they are failing...

**Comment by WilcoFiers** [comment]
Wasn't getting that before, had to reinstall my node modules to reproduce. I had a quick look but can't figure out what's going wrong. I'll have to take a deeper dive later.

**Comment by WilcoFiers** [comment]
I'm not going to fix this. It's something with PhantomJS. Instead I'm switching us to headless Chrome #36.

**Pull request closed without merging**
